"""Crear modelos

Revision ID: b9d6ffe611ea
Revises: 
Create Date: 2024-06-07 18:03:53.687102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d6ffe611ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('imagen_recognition_face', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'user', ['imagen_recognition_face'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'imagen_recognition_face')
    # ### end Alembic commands ###
